
import { Theme } from './types';

export const DEFAULT_THEME: Theme = {
  id: 'default-blue',
  name: 'Azul Profundo',
  background: 'linear-gradient(135deg, #1e3a8a 0%, #0f172a 100%)',
  aspectRatio: '16/9',
  padding: 4,
  textColor: '#ffffff',
  textBackgroundColor: 'transparent',
  textOpacity: 1,
  fontFamily: 'Montserrat, sans-serif',
  fontSize: 'text-9xl',
  fontWeight: 'bold',
  fontStyle: 'normal',
  textDecoration: 'none',
  textTransform: 'none',
  alignment: 'center',
  lineHeight: 1.2,
  letterSpacing: 0,
  shadow: true,
  shadowColor: 'rgba(0,0,0,0.8)',
  shadowBlur: 10,
  shadowOffsetX: 4,
  shadowOffsetY: 4,
  textStrokeWidth: 0,
  textStrokeColor: '#000000',
  animation: 'fade',
  bgImageBlur: 0,
  bgBrightness: 1,
  bgOverlayOpacity: 0,
  bgOverlayColor: '#000000',

  // Text Styling Extra
  textRotation: 0,
  textSkewX: 0,
  textHighlightPadding: 8,
  textHighlightRadius: 4,
  textGradient: null,
  textCase: 'none',
  textShadowSpread: 0,

  // Default Image Content Styling
  imageContentFit: 'contain',
  imageContentScale: 1.0,
  imageContentOpacity: 1.0,
  imageContentBrightness: 1.0,
  imageContentContrast: 1.0,
  imageContentSaturate: 1.0,
  imageContentGrayscale: 0,
  imageContentSepia: 0,
  imageContentHueRotate: 0,
  imageContentInvert: 0,
  imageContentBlur: 0,
  imageContentRotation: 0,
  imageContentFlipH: false,
  imageContentFlipV: false,
  imageContentRadius: 0,
  imageContentBorderWidth: 0,
  imageContentBorderColor: '#ffffff',
  imageContentShadowBlur: 0,
  imageContentShadowColor: 'rgba(0,0,0,0.5)',
  imageContentShadowOffsetX: 0,
  imageContentShadowOffsetY: 0,
  imageContentBlendMode: 'normal'
};

export const THEME_PRESETS: Theme[] = [
  DEFAULT_THEME,
  // ADORACIÓN / WORSHIP
  {
    ...DEFAULT_THEME,
    id: 'warm-worship',
    name: '🙏 Adoración Cálida',
    background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    textColor: '#fef3c7',
    fontFamily: 'Playfair Display, serif',
    fontWeight: '700',
    animation: 'fade-slide-up',
  },
  {
    ...DEFAULT_THEME,
    id: 'glory-gold',
    name: '✨ Gloria Dorada',
    background: 'linear-gradient(135deg, #0c0c0c 0%, #1a1a1a 50%, #2d1810 100%)',
    textColor: '#fbbf24',
    fontFamily: 'Cinzel, serif',
    fontWeight: '900',
    textStrokeWidth: 1,
    textStrokeColor: '#92400e',
    animation: 'zoom-in',
  },
  // NAVIDAD / CHRISTMAS
  {
    ...DEFAULT_THEME,
    id: 'christmas-red',
    name: '🎄 Navidad Roja',
    background: 'linear-gradient(135deg, #7f1d1d 0%, #450a0a 50%, #1c1917 100%)',
    textColor: '#fef2f2',
    fontFamily: 'Playfair Display, serif',
    fontWeight: '700',
    animation: 'fade',
  },
  {
    ...DEFAULT_THEME,
    id: 'christmas-snow',
    name: '❄️ Nieve Navideña',
    background: 'linear-gradient(180deg, #1e3a5f 0%, #0c4a6e 50%, #164e63 100%)',
    textColor: '#e0f2fe',
    fontFamily: 'Quicksand, sans-serif',
    fontWeight: '700',
    shadow: true,
    shadowColor: 'rgba(255,255,255,0.3)',
    shadowBlur: 15,
    animation: 'blur-in',
  },
  // PASCUA / EASTER
  {
    ...DEFAULT_THEME,
    id: 'easter-sunrise',
    name: '🌅 Amanecer de Pascua',
    background: 'linear-gradient(180deg, #fef3c7 0%, #fcd34d 30%, #f97316 100%)',
    textColor: '#1c1917',
    fontFamily: 'Merriweather, serif',
    fontWeight: '900',
    shadow: false,
    animation: 'zoom-elastic',
  },
  {
    ...DEFAULT_THEME,
    id: 'easter-life',
    name: '🌿 Vida Nueva',
    background: 'linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)',
    textColor: '#ecfdf5',
    fontFamily: 'Outfit, sans-serif',
    fontWeight: '700',
    animation: 'fade-slide-up',
  },
  // PENTECOSTÉS / PENTECOST
  {
    ...DEFAULT_THEME,
    id: 'pentecost-fire',
    name: '🔥 Fuego de Pentecostés',
    background: 'linear-gradient(180deg, #7c2d12 0%, #c2410c 50%, #ea580c 100%)',
    textColor: '#fffbeb',
    fontFamily: 'Bebas Neue, sans-serif',
    fontWeight: '400',
    letterSpacing: 3,
    animation: 'bounce-in',
  },
  // MODERNO / MODERN
  {
    ...DEFAULT_THEME,
    id: 'modern-dark',
    name: '🌙 Moderno Oscuro',
    background: 'linear-gradient(135deg, #0f0f0f 0%, #1a1a1a 100%)',
    textColor: '#ffffff',
    fontFamily: 'Outfit, sans-serif',
    fontWeight: '800',
    textStrokeWidth: 0,
    animation: 'fade',
  },
  {
    ...DEFAULT_THEME,
    id: 'modern-gradient',
    name: '🌈 Gradiente Vibrante',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    textColor: '#ffffff',
    fontFamily: 'Poppins, sans-serif',
    fontWeight: '900',
    animation: 'zoom-elastic',
  },
  // CLÁSICO / CLASSIC
  {
    ...DEFAULT_THEME,
    id: 'classic-hymn',
    name: '📖 Himno Clásico',
    background: 'linear-gradient(180deg, #1e293b 0%, #0f172a 100%)',
    textColor: '#f8fafc',
    fontFamily: 'Merriweather, serif',
    fontStyle: 'italic',
    fontWeight: '400',
    animation: 'fade',
  },
  // JUVENTUD / YOUTH
  {
    ...DEFAULT_THEME,
    id: 'youth-neon',
    name: '💜 Neón Juvenil',
    background: 'linear-gradient(135deg, #0f0f23 0%, #1a0a2e 100%)',
    textColor: '#e879f9',
    fontFamily: 'Unbounded, sans-serif',
    fontWeight: '700',
    textStrokeWidth: 1,
    textStrokeColor: '#7c3aed',
    shadow: true,
    shadowColor: '#c026d3',
    shadowBlur: 20,
    animation: 'bounce-in',
  },
  {
    ...DEFAULT_THEME,
    id: 'youth-electric',
    name: '⚡ Eléctrico',
    background: 'linear-gradient(135deg, #0c1445 0%, #1e1b4b 100%)',
    textColor: '#38bdf8',
    fontFamily: 'Syne, sans-serif',
    fontWeight: '800',
    shadow: true,
    shadowColor: '#0ea5e9',
    shadowBlur: 25,
    animation: 'elastic-slide',
  },
  // NIÑOS / KIDS
  {
    ...DEFAULT_THEME,
    id: 'kids-fun',
    name: '🎈 Niños Divertido',
    background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 50%, #ec4899 100%)',
    textColor: '#ffffff',
    fontFamily: 'Bungee, sans-serif',
    fontWeight: '400',
    animation: 'bounce-in',
  },
  // MEMORIAL / FUNERAL
  {
    ...DEFAULT_THEME,
    id: 'memorial-peace',
    name: '🕊️ Paz Memorial',
    background: 'linear-gradient(180deg, #1f2937 0%, #111827 100%)',
    textColor: '#d1d5db',
    fontFamily: 'Cormorant Garamond, serif',
    fontWeight: '400',
    fontStyle: 'italic',
    animation: 'fade',
  },
  // BODA / WEDDING
  {
    ...DEFAULT_THEME,
    id: 'wedding-elegant',
    name: '💒 Boda Elegante',
    background: 'linear-gradient(135deg, #fdf4ff 0%, #fae8ff 50%, #f5d0fe 100%)',
    textColor: '#581c87',
    fontFamily: 'Playfair Display, serif',
    fontWeight: '400',
    fontStyle: 'italic',
    animation: 'blur-in',
  },
];


// 20 "Word-like" Text Style Editions
export const TEXT_STYLE_EDITIONS: { name: string; style: Partial<Theme> }[] = [
  { name: 'Simple', style: { shadow: false, textStrokeWidth: 0, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none' } },
  { name: 'Negrita', style: { fontWeight: '800', shadow: false } },
  { name: 'Sombra Suave', style: { shadow: true, shadowBlur: 10, shadowColor: 'rgba(0,0,0,0.5)', shadowOffsetX: 2, shadowOffsetY: 2 } },
  { name: 'Sombra Dura', style: { shadow: true, shadowBlur: 0, shadowColor: '#000000', shadowOffsetX: 6, shadowOffsetY: 6 } },
  { name: 'Contorno', style: { textStrokeWidth: 2, textStrokeColor: '#ffffff', textColor: 'transparent', shadow: false } },
  { name: 'Contorno Negro', style: { textStrokeWidth: 3, textStrokeColor: '#000000', textColor: '#ffffff' } },
  { name: 'Neon Azul', style: { textColor: '#e0f2fe', shadow: true, shadowColor: '#0ea5e9', shadowBlur: 20, shadowOffsetX: 0, shadowOffsetY: 0, textStrokeWidth: 1, textStrokeColor: '#0ea5e9' } },
  { name: 'Neon Rosa', style: { textColor: '#fce7f3', shadow: true, shadowColor: '#ec4899', shadowBlur: 20, shadowOffsetX: 0, shadowOffsetY: 0, textStrokeWidth: 1, textStrokeColor: '#ec4899' } },
  { name: 'Retro 3D', style: { shadow: true, shadowColor: '#ea580c', shadowBlur: 0, shadowOffsetX: 8, shadowOffsetY: 8, textColor: '#fef3c7' } },
  { name: 'Elegante', style: { fontFamily: 'Playfair Display, serif', fontStyle: 'italic', letterSpacing: 2, fontWeight: 'normal' } },
  { name: 'Impacto', style: { fontFamily: 'Oswald, sans-serif', textTransform: 'uppercase', fontWeight: '800', letterSpacing: 1 } },
  { name: 'Subrayado', style: { textDecoration: 'underline' } },
  { name: 'Resaltado', style: { textBackgroundColor: '#facc15', textColor: '#000000' } },
  { name: 'Etiqueta', style: { textBackgroundColor: '#000000', textColor: '#ffffff', padding: 2 } },
  { name: 'Metal', style: { background: 'linear-gradient(to bottom, #9ca3af, #374151)', textColor: 'transparent', bgClip: 'text' } }, // Note: bgClip requires specific rendering handling
  { name: 'Glitch', style: { shadow: true, shadowColor: 'red', shadowOffsetX: -2, shadowOffsetY: 0, textStrokeWidth: 1, textStrokeColor: 'cyan' } },
  { name: 'Carta', style: { fontFamily: 'Courier New, monospace', fontWeight: 'normal', letterSpacing: -1 } },
  { name: 'Cine', style: { fontFamily: 'Impact, sans-serif', textStrokeWidth: 1, textStrokeColor: '#000', shadow: true, shadowBlur: 20, shadowColor: 'rgba(0,0,0,0.8)' } },
  { name: 'Minimal', style: { fontWeight: '300', letterSpacing: 4, textTransform: 'uppercase', shadow: false } },
  { name: 'Gótico', style: { fontFamily: 'Oswald, sans-serif', fontWeight: 'bold', textStrokeWidth: 1, textStrokeColor: '#4a0404', textColor: '#991b1b' } },
];

export const MOCK_PLAYLIST_ITEM_ID = 'mock-1';
